// import library functionality
import React, { useState, useEffect } from 'react';

// import custom functionality
import siteContent from '../content';
import { empty } from '../helpers';

// import components
import Head from 'next/head'

export default function Home(props) {

  const { host } = props;
  const [loading, setLoading] = useState(true);
  const [content, setContent] = useState(null);

  useEffect(() => {
    setContent(siteContent[host])
  }, [host]);

  useEffect(() => {
    if (loading && !empty(content)) {
      setLoading(false);
    }
  }, [content])

  return (
    <>
      {loading ? (
        <></>
      ) : (
        <div className="app-container">
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main>
            <h1>{content.bandName}</h1>
          </main>

          <footer>
            <p>&copy; Copyright {new Date().getFullYear()} Rustin Dodd.  All rights reserved.</p>
          </footer>
        </div>
      )}
    </>
  )
}
